
name: CI

on:
  push:

jobs:
  
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: "ancient-tundra-90402"
        run: |
          heroku container:login
          heroku container:push web -a $(appname)
          heroku container:release web -a $(appname)
